In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [86]:
#overlap add method

x=np.array([1,2,3,4])
h=np.array([1,1,1])

M=len(h)
L=M
N=L+M-1
if L!=2*M:
    x=np.append(x,np.zeros(2*M-len(x)))
h=np.append(h,np.zeros(N-M))
j=np.array_split(x,N-M)
y=[]
for i in j:
    i=np.append(i,np.zeros(N-M))
    y.append(i)
r=[]
for t in y:
    r.append(circular_covolution(t,h))

print(r)
for i in range(len(r)-1):
    u=np.array(r[i][0:M])
    v=np.array(r[i][M:M+2])
    e=np.array(r[i+1][0:M-1])
    u=np.append(u,np.add(v,e))
    o=np.array(r[i+1][M-1:M+2])
    u=np.append(u,o)
    print(u)





[[1.0, 3.0, 6.0, 5.0, 3.0], [4.0, 4.0, 4.0, 0.0, 0.0]]
[1. 3. 6. 9. 7. 4. 0. 0.]


In [31]:
def circular_convolution(x,h):
    y=[]
    a=np.array(x[0])
    b=np.array(x[:0:-1])
    p=np.insert(b,0,a)
    y.append(p)
    for i in range(len(x)-1):
        p = np.roll(p,1)
        y.append(p)
    u=[]
    for t in y:
        u.append(np.dot(t,h))
    return u
        

In [81]:

u=np.array(r[0][0:M])
v=np.array(r[0][M:M+2])
e=np.array(r[1][0:M-1])
u=np.append(u,np.add(v,e))
o=np.array(r[1][M-1:M+2])
u=np.append(u,o)
print(u)

[4. 0. 0.]
[1. 3. 6. 9. 7. 4. 0. 0.]


In [71]:
np.array(r[1][M-1:M+2])

array([4., 0., 0.])

In [85]:
for i in range(len(r)-1):
    u=np.array(r[i][0:M])
    v=np.array(r[i][M:M+2])
    e=np.array(r[i+1][0:M-1])
    u=np.append(u,np.add(v,e))
    o=np.array(r[i+1][M-1:M+2])
    u=np.append(u,o)
    print(u)

[1. 3. 6. 9. 7. 4. 0. 0.]
